export const ENDPOINTS = {
  ADMIN: {
    OVERVIEW: '/admin/overview',
    STATISTICS: '/admin/statistics',
    COMMUNITIES: '/admin/communities',
    COMMUNITIES_PENDING: '/admin/communities',
    COMMUNITIES_APPROVE: (id: string) => `/admin/communities/${id}/approve`,
    COMMUNITIES_REJECT: (id: string) => `/admin/communities/${id}/deny`,
    COMMUNITIES_SUSPEND: (id: string) => `/admin/communities/${id}/suspend`,
    COMMUNITIES_TERMINATE: (id: string) => `/admin/communities/${id}/terminate`,
    COMMUNITIES_REACTIVATE: (id: string) => `/admin/communities/${id}/reactivate`,
    COMMUNITIES_UPDATE: (id: string) => `/communities/${id}`,
    REPORTS: '/admin/reports',
    REPORT_ACTION: (id: string) => `/admin/reports/${id}/action`,
    SUBSCRIPTIONS: '/admin/subscriptions',
    PAYMENTS: '/admin/payments',
    AUDIT: '/admin/audit',
    AUDIT_LOG: '/admin/audit/log',
    // Applications Management
    APPLICATIONS: '/admin/applications',
    APPLICATIONS_BY_ROLE: (role: string) => `/admin/applications?role=${role}`,
    APPLICATION_DETAIL: (id: string) => `/admin/applications/${id}`,
    APPLICATION_APPROVE: (id: string) => `/admin/applications/${id}/approve`,
    APPLICATION_REJECT: (id: string) => `/admin/applications/${id}/reject`,
    APPLICATION_SUSPEND: (id: string) => `/admin/applications/${id}/suspend`,
    APPLICATION_REACTIVATE: (id: string) => `/admin/applications/${id}/reactivate`,
    RIDER_APPLICATION_APPROVE: (id: string) => `/admin/riders/applications/${id}/approve`,
    RIDER_APPLICATION_DENY: (id: string) => `/admin/riders/applications/${id}/deny`,
    RIDER_APPLICATION_SUSPEND: (id: string) => `/admin/riders/applications/${id}/suspend`,
    // Rider Statistics
    RIDERS: '/admin/riders',
    RIDERS_STATISTICS: '/admin/riders/statistics',
    RIDERS_TOP_PERFORMERS: '/admin/riders/top-performers',
    RIDERS_ACTIVITY_FEED: '/admin/riders/activity-feed',
    RIDERS_TREND_DATA: '/admin/riders/trend-data',
    RIDERS_OVERVIEW: '/admin/riders/overview',
    // public endpoint for the rider list (not admin scoped)
    RIDERS_LIST: '/riders/list',
    // User Management
    USERS: '/admin/users',
    USER_DETAIL: (id: string) => `/admin/users/${id}`,
    USER_UPDATE_ROLE: (id: string) => `/admin/users/${id}/role`,
    USER_UPDATE_STATUS: (id: string) => `/admin/users/${id}/status`,
    USER_DELETE: (id: string) => `/admin/users/${id}`,
    // Rider Credits Management
    GRANT_CREDITS: '/api/services/admin/credits/grant',
    DEDUCT_CREDITS: '/api/services/admin/credits/deduct',
    CREDIT_HISTORY: '/api/services/admin/credits/history',
    CREDIT_HISTORY_ALL: '/api/services/admin/credits/history/all',
    USER_CREDITS: '/api/services/admin/users',
    PLAN_STATISTICS: '/api/services/admin/credits/statistics',
    PENDING_PURCHASES: '/api/services/admin/credits/purchases/pending',
    // Document Management
    DOCUMENT_VERIFY: (id: string) => `/documents/${id}/verify`,
  },
  ANNOUNCEMENTS: {
    CREATE: '/announcements',
    ACTIVE: '/announcements/active',
    UPDATE: (id: string) => `/announcements/${id}`,
    DELETE: (id: string) => `/announcements/${id}`,
  },
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    LOGOUT: '/auth/logout',
  },
  COMMUNITIES: {
    LIST: '/communities',
    REPORT: '/communities/report',
    REPORTS: '/communities/reports',
    CALENDAR: '/communities/calendar',
    JOIN: (id: string) => `/communities/${id}/join`,
    LEAVE: (id: string) => `/communities/${id}/leave`,
  }
};
